import { Servico } from "@/src/types";

export const mockServices: Servico[] = [
    {
        title: "Migração Cloud ERP",
        clientName: "TechSoft Ltda.",
        category: "Consultoria",
        status: "em_andamento" as const,
        priority: "alta" as const,
        progress: 65,
        value: "R$ 12.000",
        deadline: "28/02/2026",
    },
    {
        title: "Redesign Website",
        clientName: "Digital Wave",
        category: "Design",
        status: "em_andamento" as const,
        priority: "media" as const,
        progress: 30,
        value: "R$ 8.500",
        deadline: "15/03/2026",
    },
    {
        title: "Manutenção Server Pro",
        clientName: "Alfa Comércio",
        category: "Infraestrutura",
        status: "concluido" as const,
        priority: "baixa" as const,
        progress: 100,
        value: "R$ 3.200",
        deadline: "10/02/2026",
    },
    {
        title: "App Mobile Delivery",
        clientName: "Marina Silva",
        category: "Desenvolvimento",
        status: "aguardando" as const,
        priority: "alta" as const,
        progress: 0,
        value: "R$ 25.000",
        deadline: "30/03/2026",
    },
    {
        title: "Campanha SEO",
        clientName: "Studio Criativo",
        category: "Marketing",
        status: "cancelado" as const,
        priority: "baixa" as const,
        progress: 15,
        value: "R$ 4.800",
        deadline: "20/02/2026",
    },
];
