export const mockClients = [
    {
        companyName: "TechSoft Ltda.",
        contactName: "Carlos Mendes",
        status: "ativo" as const,
        budgets: 8,
        conversion: "87%",
        total: "R$ 34.500",
        lastContact: "Hoje",
    },
    {
        companyName: "Digital Wave",
        contactName: "Ana Souza",
        status: "ativo" as const,
        budgets: 5,
        conversion: "60%",
        total: "R$ 18.200",
        lastContact: "Ontem",
    },
    {
        companyName: "Innovatech",
        contactName: "Roberto Lima",
        status: "pendente" as const,
        budgets: 3,
        conversion: "33%",
        total: "R$ 7.800",
        lastContact: "Há 3 dias",
    },
    {
        companyName: "CloudBase Systems",
        contactName: "Fernanda Costa",
        status: "ativo" as const,
        budgets: 12,
        conversion: "92%",
        total: "R$ 52.000",
        lastContact: "Hoje",
    },
    {
        companyName: "StartUp X",
        contactName: "João Pereira",
        status: "inativo" as const,
        budgets: 2,
        conversion: "0%",
        total: "R$ 0",
        lastContact: "Há 30 dias",
    },
];
