export const mockBudgets = [
    {
        code: "ORC-001",
        title: "Migração Cloud ERP",
        clientName: "TechSoft Ltda.",
        status: "aprovado" as const,
        value: "R$ 12.000",
        createdAt: "12/02/2026",
        validUntil: "28/02/2026",
    },
    {
        code: "ORC-002",
        title: "Redesign Completo",
        clientName: "Digital Wave",
        status: "pendente" as const,
        value: "R$ 8.500",
        createdAt: "10/02/2026",
        validUntil: "25/02/2026",
    },
    {
        code: "ORC-003",
        title: "App Mobile Delivery",
        clientName: "Marina Silva",
        status: "pendente" as const,
        value: "R$ 25.000",
        createdAt: "08/02/2026",
        validUntil: "22/02/2026",
    },
    {
        code: "ORC-004",
        title: "Manutenção Mensal",
        clientName: "Alfa Comércio",
        status: "aprovado" as const,
        value: "R$ 3.200",
        createdAt: "05/02/2026",
        validUntil: "20/02/2026",
    },
    {
        code: "ORC-005",
        title: "Campanha SEO",
        clientName: "Studio Criativo",
        status: "recusado" as const,
        value: "R$ 4.800",
        createdAt: "01/02/2026",
        validUntil: "15/02/2026",
    },
];
